query GetBowlDetailsCG($params: GetBowlDetailsParams!) {
  getBowlDetailsCG(params: $params) {
    ...FishbowlBowlCG
    ...FeedPreviewCG
  }
}
fragment FishbowlBowlCG on Feed {
  canJoin
  hasPosts
  isJoined
  isBowlLeader
  feedState {
    lastMessageDate
  }
  uiConfig {
    colorTo
    colorFrom
    icon
    coverPic
  }
  requestToJoinConfig {
    isJoinReasonRequired
    shouldRequestPhoto
    isMultipleChoiceEnabled
    userEnteredJoinReason
  }
  userPushState {
    isPushEnabled
    isNewPostsEnabled
  }
  creationDate
  subscriptionType
  suggestionSource
  joinState
  name
  isVisible
  isLocked
  handleUrl
  description
  joinMode
  type
  allowedMembershipType
  hideNumberOfUsers
  _id
  numberOfUsers
  meetsJoinRules
}
fragment FeedPreviewCG on FeedPreview {
  _id
  name
  numberOfUsers
  isVisible
  hideNumberOfUsers
  handleUrl
  description
  joinMode
  type
  joinState
  uiConfig {
    colorTo
    colorFrom
    icon
    coverPic
  }
  isJoined
  isBowlLeader
  canJoin
}
